### User registration
POST http://localhost:3000/users/register
Content-Type: application/json

{
  "email": "test@gmail.com",
  "password": "123123"
}

### Login
POST http://localhost:3000/users/login
Content-Type: application/json

{
  "email": "test101@test.com",
  "password": "123123"
}

### Delete User
DELETE http://localhost:3000/users/me
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZW1haWwiOiJ0ZXN0MTA1QGdtYWlsLmNvbSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzM2NzI5Njg2LCJleHAiOjE3MzY3MzMyODZ9.yV5fXBNuuoNMWT2in7HltESDzE75Gs1RkLGlnyWvR0E

### Update user data (including avatar)
PATCH http://localhost:3000/users/me
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiZW1haWwiOiJ0ZXN0MTExQGdtYWlsLmNvbSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzM2NzQzMzg3LCJleHAiOjE3MzY3NDY5ODd9.4cKjFMoUfeBDpRqpQ4MPBSLlO_GWtPqF2RtBCihzwa4
Content-Type: multipart/form-data; boundary=----MyTest

------MyTest
Content-Disposition: form-data; name="avatar"; filename="test.png"
Content-Type: image/png

< ./test.png

------MyTest
Content-Disposition: form-data; 
Content-Type: application/json

{
  "name": "New Name",
}
------MyTest--

### Send email
POST http://localhost:3000/users/forgot-password
Content-Type: application/json

{
  "email": "thesheleng@gmail.com"
}

### Reset password
POST http://localhost:3000/users/reset-password
Content-Type: application/json

{
  "token": "your-reset-token",
  "newPassword": "newSecurePassword123"
}